--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/suku/wallpaper/city_bridge.jpg"

-- Special
background="#020406"
foreground="#bfc0c0"
cursor="#bfc0c0"

-- Colors
color0="#020406"
color1="#284F76"
color2="#525F61"
color3="#8A796B"
color4="#305988"
color5="#196497"
color6="#2961AB"
color7="#bfc0c0"
color8="#414244"
color9="#284F76"
color10="#525F61"
color11="#8A796B"
color12="#305988"
color13="#196497"
color14="#2961AB"
color15="#bfc0c0"
