# Shell variables
# Generated by 'wal'
wallpaper="/home/suku/wallpaper/city_bridge.jpg"

# Special
background='#020406'
foreground='#bfc0c0'
cursor='#bfc0c0'

# Colors
color0='#020406'
color1='#284F76'
color2='#525F61'
color3='#8A796B'
color4='#305988'
color5='#196497'
color6='#2961AB'
color7='#bfc0c0'
color8='#414244'
color9='#284F76'
color10='#525F61'
color11='#8A796B'
color12='#305988'
color13='#196497'
color14='#2961AB'
color15='#bfc0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
